In [ ]:
# Ayush YES WE DO 
# Indexing  in numpy 





SyntaxError: invalid syntax (4180805390.py, line 1)

In [15]:
import numpy as np

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[:,3:]


array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [16]:
b =np.array([1,2,3,4,5])
a =np.array([5,6,7,4,3])
print(a+b)
print(b/a)
print(b*a)
print(b-a)
print(b%a)
print(b**a)

[ 6  8 10  8  8]
[0.2        0.33333333 0.42857143 1.         1.66666667]
[ 5 12 21 16 15]
[-4 -4 -4  0  2]
[1 2 3 0 2]
[   1   64 2187  256  125]


In [ ]:
  # Deep shallow copy

In [17]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice= a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a

NameError: name 'a' is not defined

In [21]:
a[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [ ]:
# tiem is 1:18

In [25]:
arr1= np.array([1,2,4,5,6,7,3,4,5,])
arr2 = np.array([1,2,4,5,6,7,3,4,5,])

In [26]:
arr1

array([1, 2, 4, 5, 6, 7, 3, 4, 5])

In [27]:
arr1 @ arr2

np.int64(181)

In [28]:
np.dot(arr1,arr2)

np.int64(181)