In [37]:
# Ayush YES WE DO 
# Indexing  in numpy 





In [38]:
import numpy as np

In [39]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
arr[:,3:]


array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [41]:
b =np.array([1,2,3,4,5])
a =np.array([5,6,7,4,3])
print(a+b)
print(b/a)
print(b*a)
print(b-a)
print(b%a)
print(b**a)

[ 6  8 10  8  8]
[0.2        0.33333333 0.42857143 1.         1.66666667]
[ 5 12 21 16 15]
[-4 -4 -4  0  2]
[1 2 3 0 2]
[   1   64 2187  256  125]


In [42]:
  # Deep shallow copy

In [43]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice= a[:5]
slice = slice * 10
slice
# sliceing 

array([10, 20, 30, 40, 50])

In [45]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a[2:]
# indexing wise find 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [47]:
# tiem is 1:18

In [48]:
arr1= np.array([1,2,4,5,6,7,3,4,5,])
arr2 = np.array([1,2,4,5,6,7,3,4,5,])

In [49]:
arr1

array([1, 2, 4, 5, 6, 7, 3, 4, 5])

In [73]:
arr1 @ arr2

np.int64(181)

In [51]:
np.dot(arr1,arr2)

np.int64(181)

In [52]:
prr1 = np.array([1,2,3,4])
brr1 = np.array([5,6,7,8])

In [57]:
np.vstack((prr1,brr1))
# print seprate seprate 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
np.hstack((prr1,brr1))
# marge and print 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.column_stack((prr1,brr1))
# print in coloum wise 

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [63]:
c = np.arange(16).reshape(4,4)
# creating 16 and 4 coloum array 
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [70]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]