1. Valid Sodoku 


In [163]:
import numpy as np 

In [164]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [165]:
b= np.sum(s,axis=1)
for i in b:
  print(i)
  if i !=45:
    print("soduku  is not valid ")
    break
else:
  print("for rows it is valid")

45
45
45
45
45
45
45
45
45
for rows it is valid


In [166]:
c= np.sum(s,axis=1)
for i in b:
  print(i)
  if i !=45:
    print("soduku  is not valid ")
    break
else:
  print("for coloum it is valid")

45
45
45
45
45
45
45
45
45
for coloum it is valid


In [167]:
s[0:5,0:3]

# 0 - for row
# 5 and 3 for coloum  

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8],
       [8, 5, 9],
       [4, 2, 6]])

In [168]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:1+3,j:j+3]
        print(n.sum())

67
59
54
22
14
9
0
0
0


General Question


In [169]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [170]:
# find the shape of the matrix
data.shape
# shape mean give you data to coloum and row in data 
# (5,3) 5 for rows and 3 is coloum 

(5, 3)

In [171]:
# find the avarage age of the student 

np.mean(data[:,0])


np.float64(18.4)

In [172]:
# Exteact math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [173]:
# find the highest science marks 
np.min(data[:,2])

np.int64(70)

In [174]:
# get details of the student who scored more then 90 in math

data[data[:,1 # in row 1st
]>90]

array([[19, 92, 88]])

In [175]:
#increse math marks of all student by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [176]:
#find how many student age younger than 19
len(data[data[:,0]<19])


3

In [177]:
#calculate the avarageg marks in each subject (coloum-wise mean )
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [178]:
#get data of student who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [179]:
#replace all sciece marks < 75 with 0.
data[:,2][data[:,2]< 75 ]= 0 
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

Complete the Exercies