prac


In [591]:
import numpy as np

In [592]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [593]:
arr = np.array([[1,2,3,4],[2,3,5,6],[55,53,53,12
]])
arr

array([[ 1,  2,  3,  4],
       [ 2,  3,  5,  6],
       [55, 53, 53, 12]])

In [594]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [595]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [596]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [597]:
np.linspace(0,1,2)

array([0., 1.])

In [598]:
arr= np.array([6,7,8,9])
brr= np.array([6,7,8,9])
print(arr+brr)
print(arr*brr)
print(arr/brr)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

# means 2 rows 3 coloum 
print(arr.reshape(3,2))

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr= np.array([10,20,30,40,50])
print(arr[2:4])
# indexing  & slicing 

[30 40]


In [ ]:
arr1 = np.array([[1,2],[3,4],[5,6]])
print(arr1[1,1])

4


In [ ]:
arr = np.array([1,3,4,5,6,8,9])
print(arr[arr >= 3])
# is called conditional filtering 

[3 4 5 6 8 9]


In [ ]:
#usefull mathods
arr = np.array([1,2,4,5,6])
print(np.sum(arr))#15
print(np.std(arr)) # 3.0
print(np.mean(arr)) #std for standerd deviation
print(np.max(arr))#5
print(np.min(arr))#1



18
1.8547236990991407
3.6
6
1


In [ ]:
a = np.array([1,2,3,5])
b = np.array([4,5,6,7])

In [ ]:
print(a+b)
print(a-b)
print(a*b)

[ 5  7  9 12]
[-3 -3 -3 -2]
[ 4 10 18 35]


In [ ]:
random = np.random.randint(1,30,(2,2))
#i to 30 range gives random numbers 
print(random)

[[16  1]
 [19 10]]


In [ ]:
random[random>3]

array([16, 19, 10], dtype=int32)

In [ ]:
a1 = np.array([[2,4],[3,6]])
a2 = np.array([[5,1],[8,1]])
# result = np.dot(a1,a2)
result = a1 @ a2
result
# print(result)
# .dot and @  and matmul use for multiplication  in matrix 


array([[42,  6],
       [63,  9]])

In [ ]:
result

array([[31, 36],
       [33, 38]])

In [ ]:
a = np.ones((2,1,3))
b = np.ones((2,3,4))
print =(np.matmul(a,b).shape)



TypeError: 'tuple' object is not callable

pratice markdown


In [ ]:
A = np.array([[4,3],[1,4]])
B = np.array(([3,6],[4,2])) 
# ap = (A@B) # frist mathod 
# np.matmul(A,B) # second mathod 
np.dot(A,B) #third Mathod
# ap

array([[24, 30],
       [19, 14]])

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
np.dot(A,B) #third Mathod


array([[ 58,  64],
       [139, 154]])

In [ ]:
A = np.array([[10, 20],
              [30, 40]])
A

array([[10, 20],
       [30, 40]])

In [599]:
P = np.array([[1,2],
              [3,4],
              [5,6]])
B= np.array([[7,8,9],
             [10,11,12]])
result = (P@B)
result


array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])